// ═══════════════════════════════════════════════════════════════════
// MathVerse Mock Data — Full world tree: 4 realms × 3 districts × 3 nodes
// ═══════════════════════════════════════════════════════════════════

export const REALMS = [
  {
    id: 'realm_grade1',
    grade: 1,
    name: 'Grade 1',
    theme: 'beach',
    tagline: 'Numbers, counting & comparison',
    color: '#4ade80',
    gradientFrom: '#22c55e',
    gradientTo: '#38bdf8',
    isUnlocked: true,
    masteryPercent: 0,
    position: [-6, 0, -4],
    districts: ['district_numbers', 'district_counting', 'district_comparison'],
  },
  {
    id: 'realm_grade2',
    grade: 2,
    name: 'Grade 2',
    theme: 'shore',
    tagline: 'Addition & subtraction',
    color: '#34d399',
    gradientFrom: '#059669',
    gradientTo: '#38bdf8',
    isUnlocked: true,
    masteryPercent: 0,
    position: [-4, 0, -8],
    districts: [],
  },
  {
    id: 'realm_grade3',
    grade: 3,
    name: 'Grade 3',
    theme: 'marsh',
    tagline: 'Multiplication & division',
    color: '#86efac',
    gradientFrom: '#059669',
    gradientTo: '#84cc16',
    isUnlocked: true,
    masteryPercent: 0,
    position: [-2, 0, -2],
    districts: ['district_multiples', 'district_times_tables', 'district_division'],
  },
  {
    id: 'realm_grade4',
    grade: 4,
    name: 'Grade 4',
    theme: 'crystal',
    tagline: 'Fractions & decimals',
    color: '#22d3ee',
    gradientFrom: '#0891b2',
    gradientTo: '#a78bfa',
    isUnlocked: true,
    masteryPercent: 0,
    position: [2, 0, 0],
    districts: ['district_intro_fractions', 'district_equiv_fractions', 'district_fraction_ops'],
  },
  {
    id: 'realm_grade5',
    grade: 5,
    name: 'Grade 5',
    theme: 'dunes',
    tagline: 'Decimals, percentages & ratios',
    color: '#fbbf24',
    gradientFrom: '#d97706',
    gradientTo: '#f59e0b',
    isUnlocked: true,
    masteryPercent: 0,
    position: [5, 0, -8],
    districts: [],
  },
  {
    id: 'realm_grade6',
    grade: 6,
    name: 'Grade 6',
    theme: 'mystic',
    tagline: 'Algebra & expressions',
    color: '#a855f7',
    gradientFrom: '#7c3aed',
    gradientTo: '#2563eb',
    isUnlocked: true,
    masteryPercent: 0,
    position: [6, 0, -3],
    districts: ['district_variables', 'district_equations', 'district_expressions'],
  },
  {
    id: 'realm_grade7',
    grade: 7,
    name: 'Grade 7',
    theme: 'gardens',
    tagline: 'Geometry & measurement',
    color: '#f472b6',
    gradientFrom: '#db2777',
    gradientTo: '#a855f7',
    isUnlocked: true,
    masteryPercent: 0,
    position: [10, 0, -2],
    districts: [],
  },
  {
    id: 'realm_grade8',
    grade: 8,
    name: 'Grade 8',
    theme: 'peaks',
    tagline: 'Statistics & probability',
    color: '#60a5fa',
    gradientFrom: '#2563eb',
    gradientTo: '#06b6d4',
    isUnlocked: true,
    masteryPercent: 0,
    position: [9, 0, -10],
    districts: [],
  },
  {
    id: 'realm_grade9',
    grade: 9,
    name: 'Grade 9',
    theme: 'tundra',
    tagline: 'Trigonometry & functions',
    color: '#818cf8',
    gradientFrom: '#4f46e5',
    gradientTo: '#7c3aed',
    isUnlocked: true,
    masteryPercent: 0,
    position: [2, 0, -14],
    districts: [],
  },
  {
    id: 'realm_grade10',
    grade: 10,
    name: 'Grade 10',
    theme: 'citadel',
    tagline: 'Calculus & advanced algebra',
    color: '#f87171',
    gradientFrom: '#dc2626',
    gradientTo: '#f97316',
    isUnlocked: true,
    masteryPercent: 0,
    position: [-2, 0, -16],
    districts: [],
  },
]

export const DISTRICTS = {
  // ── Grade 1 Districts ─────────────────────────────────────────
  district_numbers: {
    id: 'district_numbers', realmId: 'realm_grade1',
    name: 'Number Island', landmark: 'number_cave',
    color: '#4ade80', isUnlocked: true, masteryPercent: 100,
    nodes: ['node_counting_1', 'node_counting_2', 'node_counting_3'],
  },
  district_counting: {
    id: 'district_counting', realmId: 'realm_grade1',
    name: 'Counting Cove Beach', landmark: 'sandcastle',
    color: '#4ade80', isUnlocked: true, masteryPercent: 100,
    nodes: ['node_skip_count_1', 'node_skip_count_2', 'node_skip_count_3'],
  },
  district_comparison: {
    id: 'district_comparison', realmId: 'realm_grade1',
    name: 'Comparison Cliffs', landmark: 'balance_rock',
    color: '#4ade80', isUnlocked: true, masteryPercent: 100,
    nodes: ['node_compare_1', 'node_compare_2', 'node_compare_3'],
  },

  // ── Grade 3 Districts ─────────────────────────────────────────
  district_multiples: {
    id: 'district_multiples', realmId: 'realm_grade3',
    name: 'Multiples Meadow', landmark: 'lily_pad',
    color: '#34d399', isUnlocked: true, masteryPercent: 100,
    nodes: ['node_mult_1', 'node_mult_2', 'node_mult_3'],
  },
  district_times_tables: {
    id: 'district_times_tables', realmId: 'realm_grade3',
    name: 'Times-Table Trails', landmark: 'stepping_stone',
    color: '#34d399', isUnlocked: true, masteryPercent: 100,
    nodes: ['node_times_1', 'node_times_2', 'node_times_3'],
  },
  district_division: {
    id: 'district_division', realmId: 'realm_grade3',
    name: 'Division Dell', landmark: 'split_tree',
    color: '#34d399', isUnlocked: false, masteryPercent: 0,
    nodes: ['node_div_1', 'node_div_2', 'node_div_3'],
  },

  // ── Grade 4 Districts ─────────────────────────────────────────
  district_intro_fractions: {
    id: 'district_intro_fractions', realmId: 'realm_grade4',
    name: 'Fraction Gateway', landmark: 'crystal_arch',
    color: '#22d3ee', isUnlocked: true, masteryPercent: 100,
    nodes: ['node_frac_intro_1', 'node_frac_intro_2', 'node_frac_intro_3'],
  },
  district_equiv_fractions: {
    id: 'district_equiv_fractions', realmId: 'realm_grade4',
    name: 'Equivalent Grove', landmark: 'fraction_bridge',
    color: '#22d3ee', isUnlocked: true, masteryPercent: 0,
    nodes: ['node_equiv_1', 'node_equiv_2', 'node_equiv_3'],
  },
  district_fraction_ops: {
    id: 'district_fraction_ops', realmId: 'realm_grade4',
    name: 'Operations Outpost', landmark: 'ice_tower',
    color: '#22d3ee', isUnlocked: false, masteryPercent: 0,
    nodes: ['node_frac_add_1', 'node_frac_add_2', 'node_frac_add_3'],
  },

  // ── Grade 6 Districts ─────────────────────────────────────────
  district_variables: {
    id: 'district_variables', realmId: 'realm_grade6',
    name: 'Variable Vault', landmark: 'rune_stone',
    color: '#a855f7', isUnlocked: true, masteryPercent: 0,
    nodes: ['node_var_1', 'node_var_2', 'node_var_3'],
  },
  district_equations: {
    id: 'district_equations', realmId: 'realm_grade6',
    name: 'Equation Engine', landmark: 'algebra_tower',
    color: '#a855f7', isUnlocked: false, masteryPercent: 0,
    nodes: ['node_eq_1', 'node_eq_2', 'node_eq_3'],
  },
  district_expressions: {
    id: 'district_expressions', realmId: 'realm_grade6',
    name: 'Expression Expanse', landmark: 'mystic_gate',
    color: '#a855f7', isUnlocked: false, masteryPercent: 0,
    nodes: ['node_expr_1', 'node_expr_2', 'node_expr_3'],
  },
}

export const SKILL_NODES = {
  // ── Grade 1 — Numbers ──────────────────────────────────────────
  node_counting_1: {
    id: 'node_counting_1', districtId: 'district_numbers',
    title: 'Recognising Numbers 1–10',
    explainer: 'Numbers are symbols that represent quantities. 1 apple, 2 apples… each number has its own name and shape!',
    story: '🌊 Captain Coral needs help counting the fish in her cove. Can you name each number?',
    status: 'mastered', difficulty: 1, xpReward: 50,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Which number comes after 4?', options: ['3','5','6','2'], answer: '5', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: 'How many 🐟 are here: 🐟🐟🐟?', options: ['2','3','4','1'], answer: '3', difficulty: 1 },
      { id: 'q3', type: 'mcq', text: 'Which number is the biggest?', options: ['7','3','9','5'], answer: '9', difficulty: 1 },
      { id: 'q4', type: 'mcq', text: 'What number is shown: VII?', options: ['5','6','7','8'], answer: '7', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: 'Count backwards: 10, 9, __, 7', options: ['6','8','5','11'], answer: '8', difficulty: 2 },
    ],
  },
  node_counting_2: {
    id: 'node_counting_2', districtId: 'district_numbers',
    title: 'Numbers 11–20',
    explainer: 'Teen numbers are made from 10 + some extras. 13 = 10 + 3 — a bundle of ten and three more!',
    story: '🦀 Crabby the crab has collected shells. Can you count them all?',
    status: 'mastered', difficulty: 1, xpReward: 50,
    questions: [
      { id: 'q1', type: 'mcq', text: 'How many is 10 + 5?', options: ['14','15','16','51'], answer: '15', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: 'Which comes between 17 and 19?', options: ['16','18','20','15'], answer: '18', difficulty: 1 },
      { id: 'q3', type: 'mcq', text: '20 is made of 10 + ?', options: ['10','5','8','12'], answer: '10', difficulty: 1 },
      { id: 'q4', type: 'mcq', text: 'Which number is NOT a teen?', options: ['13','17','20','19'], answer: '20', difficulty: 2 },
      { id: 'q5', type: 'drag', text: 'Arrange from smallest to biggest:', options: ['16','12','19','14'], answer: ['12','14','16','19'], difficulty: 2 },
    ],
  },
  node_counting_3: {
    id: 'node_counting_3', districtId: 'district_numbers',
    title: 'Numbers up to 100',
    explainer: 'A hundred is a square — 10 rows of 10. Every number up to 100 has its place in the grid!',
    story: '🐚 The hundredth shell is hidden in the sand. Use your number sense to find it!',
    status: 'mastered', difficulty: 2, xpReward: 75,
    questions: [
      { id: 'q1', type: 'mcq', text: 'What is 10 more than 43?', options: ['44','53','33','34'], answer: '53', difficulty: 2 },
      { id: 'q2', type: 'mcq', text: 'Which number has 7 tens and 2 ones?', options: ['27','72','17','271'], answer: '72', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: '56 is between…', options: ['40–50','50–60','60–70','70–80'], answer: '50–60', difficulty: 1 },
      { id: 'q4', type: 'mcq', text: 'Count by 10s: 20, 30, __, 50', options: ['35','45','40','42'], answer: '40', difficulty: 1 },
      { id: 'q5', type: 'mcq', text: 'Which is the greatest? 84, 48, 94, 49', options: ['84','48','94','49'], answer: '94', difficulty: 2 },
    ],
  },

  // ── Grade 4 — Fractions (the active realm) ───────────────────
  node_frac_intro_1: {
    id: 'node_frac_intro_1', districtId: 'district_intro_fractions',
    title: 'What is a Fraction?',
    explainer: 'A fraction tells us how many equal parts of a whole we have. ½ means one out of two equal parts — like splitting a sandwich right down the middle!',
    story: '🧊 The Crystal Bridge is broken in equal pieces. Help Princess Prism understand fractions to rebuild it!',
    status: 'mastered', difficulty: 1, xpReward: 80,
    questions: [
      { id: 'q1', type: 'mcq', text: 'A pizza is cut into 4 equal slices. You eat 1. What fraction did you eat?', options: ['1/2','1/4','1/3','4/1'], answer: '1/4', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: 'In the fraction 3/5, what is the denominator?', options: ['3','5','2','8'], answer: '5', difficulty: 1 },
      { id: 'q3', type: 'mcq', text: 'Which fraction shows "half"?', options: ['1/4','2/3','1/2','3/4'], answer: '1/2', difficulty: 1 },
      { id: 'q4', type: 'mcq', text: 'A ribbon is cut into 8 equal parts. 3 parts are blue. What fraction is blue?', options: ['3/5','8/3','3/8','5/8'], answer: '3/8', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: 'Which fraction is greater than 1/2?', options: ['1/4','2/8','3/4','1/3'], answer: '3/4', difficulty: 2 },
    ],
  },
  node_frac_intro_2: {
    id: 'node_frac_intro_2', districtId: 'district_intro_fractions',
    title: 'Fractions on a Number Line',
    explainer: 'Number lines show where fractions live between whole numbers. 1/2 sits exactly halfway between 0 and 1!',
    story: '🔷 The crystal path needs fraction markers. Place them correctly to light the way!',
    status: 'mastered', difficulty: 2, xpReward: 80,
    questions: [
      { id: 'q1', type: 'mcq', text: 'On a number line from 0 to 1, where is 1/4?', options: ['Near 0','Exactly halfway','Three-quarters of the way','Past 1'], answer: 'Near 0', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: 'Which fraction is closest to 1?', options: ['1/4','1/2','3/4','1/8'], answer: '3/4', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: '2/4 is the same point as…', options: ['1/4','3/4','1/2','1/8'], answer: '1/2', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: 'What fraction is at the midpoint between 1/2 and 1?', options: ['1/4','2/3','3/4','3/8'], answer: '3/4', difficulty: 3 },
      { id: 'q5', type: 'mcq', text: 'Order: 1/8, 1/2, 1/4, 1 — which is second?', options: ['1/8','1/2','1/4','1'], answer: '1/4', difficulty: 2 },
    ],
  },
  node_frac_intro_3: {
    id: 'node_frac_intro_3', districtId: 'district_intro_fractions',
    title: 'Fractions of a Set',
    explainer: 'Fractions don\'t just describe shapes — they describe groups! 2/5 of 10 stars = 4 stars.',
    story: '⭐ Stella needs to sort her star collection into equal groups. Use fractions to help her!',
    status: 'mastered', difficulty: 2, xpReward: 90,
    questions: [
      { id: 'q1', type: 'mcq', text: 'What is 1/2 of 10?', options: ['4','5','6','2'], answer: '5', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: 'What is 1/4 of 12?', options: ['4','3','6','2'], answer: '3', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: 'There are 8 balloons. 3/8 are red. How many red?', options: ['3','4','5','6'], answer: '3', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: 'What is 2/3 of 9?', options: ['4','5','6','3'], answer: '6', difficulty: 3 },
      { id: 'q5', type: 'mcq', text: '10 students; 2/5 like math best. How many?', options: ['2','4','5','6'], answer: '4', difficulty: 3 },
    ],
  },
  node_equiv_1: {
    id: 'node_equiv_1', districtId: 'district_equiv_fractions',
    title: 'Equivalent Fractions',
    explainer: 'Different fractions can name the same amount! 1/2 = 2/4 = 4/8 — multiply top and bottom by the same number.',
    story: '🌉 The Fraction Bridge has two sides that must balance. Show the equivalent fractions to keep it steady!',
    status: 'available', difficulty: 2, xpReward: 100,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Which fraction is equivalent to 1/2?', options: ['2/6','3/6','1/4','4/6'], answer: '3/6', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: 'Complete: 2/3 = ?/9', options: ['4','6','5','3'], answer: '6', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: '4/8 in simplest form is…', options: ['2/4','1/2','1/4','4/4'], answer: '1/2', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: 'Are 3/4 and 6/8 equivalent?', options: ['Yes','No','Only sometimes','Cannot tell'], answer: 'Yes', difficulty: 2 },
      { id: 'q5', type: 'drag', text: 'Match equivalent pairs:', options: ['1/3','2/6','3/4','6/8'], answer: ['1/3 = 2/6','3/4 = 6/8'], difficulty: 3 },
    ],
  },
  node_equiv_2: {
    id: 'node_equiv_2', districtId: 'district_equiv_fractions',
    title: 'Simplifying Fractions',
    explainer: 'To simplify a fraction, divide both top and bottom by their greatest common factor (GCF). 6/9 ÷ 3/3 = 2/3.',
    story: '💎 The Crystal Sculptor chips away the extra stone to reveal the simplest form — the true gem inside!',
    status: 'locked', difficulty: 3, xpReward: 110,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Simplify 4/6', options: ['2/3','1/2','4/6','3/4'], answer: '2/3', difficulty: 2 },
      { id: 'q2', type: 'mcq', text: 'Simplify 8/12', options: ['4/6','2/3','1/2','3/4'], answer: '2/3', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: 'Is 5/7 in its simplest form?', options: ['Yes','No','Not sure','Depends'], answer: 'Yes', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: 'What is the GCF of 6 and 9?', options: ['2','3','6','9'], answer: '3', difficulty: 3 },
      { id: 'q5', type: 'mcq', text: 'Simplify 15/20', options: ['3/5','3/4','5/7','4/5'], answer: '3/4', difficulty: 3 },
    ],
  },
  node_equiv_3: {
    id: 'node_equiv_3', districtId: 'district_equiv_fractions',
    title: 'Comparing Fractions',
    explainer: 'To compare fractions, give them the same denominator — then just compare the tops! 2/3 vs 3/4 → 8/12 vs 9/12. 3/4 wins!',
    story: '⚖️ The Scale of Justice needs balance. Which fraction is heavier?',
    status: 'locked', difficulty: 3, xpReward: 110,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Which is bigger: 1/3 or 1/4?', options: ['1/4','1/3','Equal','Cannot tell'], answer: '1/3', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: 'Compare 2/5 and 3/7. Which is larger?', options: ['2/5','3/7','Equal','Need more info'], answer: '3/7', difficulty: 3 },
      { id: 'q3', type: 'mcq', text: 'Arrange: 1/2, 2/3, 1/4, 3/4 from least to greatest', options: ['1/4, 1/2, 2/3, 3/4','1/2, 1/4, 3/4, 2/3','2/3, 3/4, 1/2, 1/4','1/4, 1/2, 3/4, 2/3'], answer: '1/4, 1/2, 2/3, 3/4', difficulty: 3 },
      { id: 'q4', type: 'mcq', text: 'Is 4/5 > 3/4?', options: ['Yes','No','Equal','Cannot determine'], answer: 'Yes', difficulty: 3 },
      { id: 'q5', type: 'mcq', text: 'What fraction is between 1/2 and 3/4?', options: ['1/4','2/3','3/8','7/8'], answer: '2/3', difficulty: 3 },
    ],
  },

  // ── Grade 6 — Algebra (first active node) ────────────────────
  node_var_1: {
    id: 'node_var_1', districtId: 'district_variables',
    title: 'What is a Variable?',
    explainer: 'A variable is a letter that stands in for an unknown number. If n + 3 = 7, then n = 4. The letter is a mystery waiting to be solved!',
    story: '🔮 The Rune Stone glows only when you find the secret number hidden in the symbols. Decode the variable!',
    status: 'available', difficulty: 3, xpReward: 120,
    questions: [
      { id: 'q1', type: 'mcq', text: 'If x = 5, what is x + 3?', options: ['7','8','9','53'], answer: '8', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: 'In 4n = 20, what is n?', options: ['4','5','6','16'], answer: '5', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: 'What does the variable represent in: y − 7 = 3?', options: ['y = 4','y = 10','y = 3','y = 7'], answer: 'y = 10', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: 'If a = 3 and b = 4, what is a + b?', options: ['34','7','1','12'], answer: '7', difficulty: 1 },
      { id: 'q5', type: 'mcq', text: 'Solve: 2m + 1 = 9', options: ['m = 4','m = 5','m = 3','m = 8'], answer: 'm = 4', difficulty: 3 },
    ],
  },

  // ── Grade 1 — Skip Counting ───────────────────────────────────
  node_skip_count_1: {
    id: 'node_skip_count_1', districtId: 'district_counting',
    title: 'Skip Counting by 2s',
    explainer: 'Skip counting means jumping over numbers in a pattern. Count by 2s: 2, 4, 6, 8… like hopping on every other stepping stone!',
    story: '🦘 Kanga the kangaroo only lands on every 2nd number. Can you predict where she lands?',
    status: 'mastered', difficulty: 1, xpReward: 50,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Count by 2s: 2, 4, 6, __', options: ['7','8','9','10'], answer: '8', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: 'Which list shows skip counting by 2?', options: ['1,2,3,4','2,4,6,8','2,3,4,5','1,3,5,7'], answer: '2,4,6,8', difficulty: 1 },
      { id: 'q3', type: 'mcq', text: 'Count by 2s: 10, 12, 14, __', options: ['15','16','17','18'], answer: '16', difficulty: 1 },
      { id: 'q4', type: 'mcq', text: 'What is the 5th number when counting by 2s from 2?', options: ['8','9','10','12'], answer: '10', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: 'Skip count by 2: 4, __, 8, 10', options: ['5','6','7','9'], answer: '6', difficulty: 1 },
    ],
  },
  node_skip_count_2: {
    id: 'node_skip_count_2', districtId: 'district_counting',
    title: 'Skip Counting by 5s',
    explainer: 'Counting by 5s is super handy — it\'s how we count nickels! 5, 10, 15, 20… your fingers on two hands!',
    story: '🖐️ The starfish collector has 5 arms. Help count her whole collection by 5s!',
    status: 'mastered', difficulty: 1, xpReward: 50,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Count by 5s: 5, 10, 15, __', options: ['16','18','20','25'], answer: '20', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: 'Which number comes next? 25, 30, 35, __', options: ['36','38','40','45'], answer: '40', difficulty: 1 },
      { id: 'q3', type: 'mcq', text: 'How many 5s make 30?', options: ['4','5','6','7'], answer: '6', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: 'Count by 5: 50, 55, 60, __', options: ['61','63','65','70'], answer: '65', difficulty: 1 },
      { id: 'q5', type: 'mcq', text: 'Skip 5: __, 15, 20, 25', options: ['5','8','10','12'], answer: '10', difficulty: 1 },
    ],
  },
  node_skip_count_3: {
    id: 'node_skip_count_3', districtId: 'district_counting',
    title: 'Skip Counting by 10s',
    explainer: 'Counting by 10s is the fastest! Every jump adds a full ten: 10, 20, 30… Each new tens-place opens up!',
    story: '🔟 The lighthouse keeper flashes his light every 10 seconds. Help him track the time!',
    status: 'mastered', difficulty: 2, xpReward: 60,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Count by 10s: 10, 20, 30, __', options: ['31','35','40','50'], answer: '40', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: 'What comes next? 60, 70, 80, __', options: ['81','85','88','90'], answer: '90', difficulty: 1 },
      { id: 'q3', type: 'mcq', text: 'Count by 10s from 35: 35, 45, __', options: ['46','50','55','56'], answer: '55', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: '10, 20, 30… what is the 7th number?', options: ['60','70','80','90'], answer: '70', difficulty: 2 },
      { id: 'q5', type: 'drag', text: 'Order these from least to greatest:', options: ['40','10','30','20'], answer: ['10','20','30','40'], difficulty: 2 },
    ],
  },

  // ── Grade 1 — Comparison ──────────────────────────────────────
  node_compare_1: {
    id: 'node_compare_1', districtId: 'district_comparison',
    title: 'Greater Than & Less Than',
    explainer: 'We use > (greater than) and < (less than) to compare numbers. Think of the sign as a hungry crocodile — it always eats the bigger number!',
    story: '🐊 The comparison crocodile is very hungry. Help him pick the bigger number to eat!',
    status: 'mastered', difficulty: 1, xpReward: 55,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Which sign goes between 7 and 4? (7 __ 4)', options: ['>','<','=','≈'], answer: '>', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: '3 __ 8 (fill in the blank)', options: ['>','<','=','+'], answer: '<', difficulty: 1 },
      { id: 'q3', type: 'mcq', text: 'Which is true?', options: ['5 > 9','9 < 5','9 > 5','5 = 9'], answer: '9 > 5', difficulty: 1 },
      { id: 'q4', type: 'mcq', text: 'Which number makes this true? __ > 6', options: ['3','4','6','7'], answer: '7', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: 'Which number is the smallest? 12, 5, 9, 18', options: ['12','5','9','18'], answer: '5', difficulty: 1 },
    ],
  },
  node_compare_2: {
    id: 'node_compare_2', districtId: 'district_comparison',
    title: 'Equal, More, or Fewer',
    explainer: 'Equal means the same amount. More means there are extra. Fewer means there are less. These words help us describe and compare groups!',
    story: '🌊 Two boats each carry treasure. Which boat carries more? Count carefully!',
    status: 'mastered', difficulty: 1, xpReward: 55,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Group A has 8 apples. Group B has 8 apples. They are…', options: ['More','Fewer','Equal','Different'], answer: 'Equal', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: '5 cats and 8 dogs — which group has fewer?', options: ['dogs','cats','equal','cannot tell'], answer: 'cats', difficulty: 1 },
      { id: 'q3', type: 'mcq', text: 'Which shows "6 is fewer than 10"?', options: ['6 > 10','6 = 10','6 < 10','10 < 6'], answer: '6 < 10', difficulty: 1 },
      { id: 'q4', type: 'mcq', text: 'If Jane has 7 stickers and Bob has 5, how many MORE does Jane have?', options: ['1','2','3','12'], answer: '2', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: 'Which pair is NOT equal?', options: ['4+4 and 8','3+5 and 9','6+2 and 8','5+3 and 8'], answer: '3+5 and 9', difficulty: 2 },
    ],
  },
  node_compare_3: {
    id: 'node_compare_3', districtId: 'district_comparison',
    title: 'Ordering Numbers',
    explainer: 'Ordering numbers means putting them in a line from smallest to biggest (ascending) or biggest to smallest (descending). Like ranking scores in a game!',
    story: '🏆 The competition scores are all mixed up! Sort them from lowest to highest.',
    status: 'mastered', difficulty: 2, xpReward: 65,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Arrange ascending: 5, 1, 9, 3', options: ['9,5,3,1','1,3,5,9','3,1,9,5','5,3,1,9'], answer: '1,3,5,9', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: 'What is the largest? 17, 71, 11, 77', options: ['17','71','11','77'], answer: '77', difficulty: 1 },
      { id: 'q3', type: 'drag', text: 'Order from smallest to biggest:', options: ['15','3','9','21'], answer: ['3','9','15','21'], difficulty: 2 },
      { id: 'q4', type: 'mcq', text: 'Which order is descending? 8, 5, 3, 1', options: ['Yes, descending','No, it\'s ascending','It\'s equal','Not ordered'], answer: 'Yes, descending', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: 'What number comes between 14 and 18?', options: ['13','14','16','19'], answer: '16', difficulty: 2 },
    ],
  },

  // ── Grade 3 — Multiples ───────────────────────────────────────
  node_mult_1: {
    id: 'node_mult_1', districtId: 'district_multiples',
    title: 'What are Multiples?',
    explainer: 'A multiple is the result of multiplying a number by any whole number. Multiples of 3: 3, 6, 9, 12… They\'re the landing pads when you skip count!',
    story: '🌸 The lily pads bloom in multiples. Jump from pad to pad — only land on multiples of 3!',
    status: 'mastered', difficulty: 2, xpReward: 80,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Which is a multiple of 4?', options: ['10','14','16','18'], answer: '16', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: 'List the first 3 multiples of 5', options: ['5,10,20','5,10,15','5,15,25','10,15,20'], answer: '5,10,15', difficulty: 1 },
      { id: 'q3', type: 'mcq', text: 'Is 24 a multiple of 6?', options: ['Yes','No','Only sometimes','Cannot tell'], answer: 'Yes', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: 'Which number is NOT a multiple of 7?', options: ['7','14','21','25'], answer: '25', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: 'What is the 4th multiple of 8?', options: ['24','28','32','36'], answer: '32', difficulty: 2 },
    ],
  },
  node_mult_2: {
    id: 'node_mult_2', districtId: 'district_multiples',
    title: 'Multiples of 2, 5, and 10',
    explainer: 'Multiples of 2 always end in 0, 2, 4, 6, or 8. Multiples of 5 end in 0 or 5. Multiples of 10 always end in 0. Spotting them is quick!',
    story: '🐸 Three frogs jump — one by 2, one by 5, one by 10. Which lily pad do they share?',
    status: 'mastered', difficulty: 2, xpReward: 80,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Is 37 a multiple of 2?', options: ['Yes','No','Maybe','Depends'], answer: 'No', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: 'Which number is a multiple of both 2 and 5?', options: ['14','15','20','25'], answer: '20', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: 'Is 85 a multiple of 5?', options: ['Yes','No','Only sometimes','Need more info'], answer: 'Yes', difficulty: 1 },
      { id: 'q4', type: 'mcq', text: 'What do all multiples of 10 end in?', options: ['5','0 or 5','0','Even digits'], answer: '0', difficulty: 1 },
      { id: 'q5', type: 'mcq', text: 'Which is a multiple of 2, 5, AND 10?', options: ['5','10','20','Both 10 and 20'], answer: 'Both 10 and 20', difficulty: 3 },
    ],
  },
  node_mult_3: {
    id: 'node_mult_3', districtId: 'district_multiples',
    title: 'Common Multiples',
    explainer: 'A common multiple is shared by two numbers. The Least Common Multiple (LCM) is the smallest one they share. LCM of 4 and 6 is 12!',
    story: '🌿 Two vines grow together — one sprouts every 4 days, one every 6. When do they sprout on the same day?',
    status: 'mastered', difficulty: 3, xpReward: 95,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Find a common multiple of 3 and 4', options: ['6','8','12','15'], answer: '12', difficulty: 2 },
      { id: 'q2', type: 'mcq', text: 'What is the LCM of 2 and 3?', options: ['2','3','6','9'], answer: '6', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: 'Is 20 a common multiple of 4 and 5?', options: ['Yes','No','4 only','5 only'], answer: 'Yes', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: 'LCM of 6 and 8 is…', options: ['12','24','48','6'], answer: '24', difficulty: 3 },
      { id: 'q5', type: 'mcq', text: 'What is the smallest number divisible by both 5 and 6?', options: ['11','20','30','60'], answer: '30', difficulty: 3 },
    ],
  },

  // ── Grade 3 — Times Tables ────────────────────────────────────
  node_times_1: {
    id: 'node_times_1', districtId: 'district_times_tables',
    title: 'Times Tables: 2s and 3s',
    explainer: 'Multiplication is fast adding! 3 × 4 means "3 added four times" = 12. Learning your tables is like having a secret shortcut map!',
    story: '🗺️ The marsh trail has shortcuts! Memorise the 2s and 3s to find the fastest path.',
    status: 'mastered', difficulty: 2, xpReward: 80,
    questions: [
      { id: 'q1', type: 'mcq', text: '3 × 4 = ?', options: ['9','10','12','14'], answer: '12', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: '2 × 7 = ?', options: ['9','12','14','16'], answer: '14', difficulty: 1 },
      { id: 'q3', type: 'mcq', text: '3 × 8 = ?', options: ['21','24','27','30'], answer: '24', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: '2 × 9 = ?', options: ['16','18','20','22'], answer: '18', difficulty: 1 },
      { id: 'q5', type: 'mcq', text: '3 × 9 = ?', options: ['24','27','30','33'], answer: '27', difficulty: 2 },
    ],
  },
  node_times_2: {
    id: 'node_times_2', districtId: 'district_times_tables',
    title: 'Times Tables: 4s and 5s',
    explainer: 'The 4s table is double the 2s! And 5s are easy — just count by fives. 5 × 6 = 30, 5 × 7 = 35…',
    story: '🎵 The marsh musicians play in groups of 4 and 5. Help them multiply their sound!',
    status: 'mastered', difficulty: 2, xpReward: 80,
    questions: [
      { id: 'q1', type: 'mcq', text: '4 × 6 = ?', options: ['20','22','24','26'], answer: '24', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: '5 × 7 = ?', options: ['30','35','40','45'], answer: '35', difficulty: 1 },
      { id: 'q3', type: 'mcq', text: '4 × 9 = ?', options: ['32','34','36','40'], answer: '36', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: '5 × 12 = ?', options: ['50','55','60','65'], answer: '60', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: 'Which gives the largest product? 4×8 or 5×6?', options: ['4×8 (32)','5×6 (30)','They\'re equal','Cannot tell'], answer: '4×8 (32)', difficulty: 2 },
    ],
  },
  node_times_3: {
    id: 'node_times_3', districtId: 'district_times_tables',
    title: 'Times Tables: 6–9',
    explainer: 'The bigger tables are trickier but have patterns! 9s: the digits always add up to 9 (9×3=27, 2+7=9). 6s: always even.',
    story: '🌟 The star-chart of multiplication! Master the 6–9 tables to unlock the cosmic compass.',
    status: 'mastered', difficulty: 3, xpReward: 95,
    questions: [
      { id: 'q1', type: 'mcq', text: '7 × 8 = ?', options: ['48','54','56','63'], answer: '56', difficulty: 2 },
      { id: 'q2', type: 'mcq', text: '9 × 6 = ?', options: ['45','48','54','63'], answer: '54', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: '8 × 8 = ?', options: ['56','60','64','72'], answer: '64', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: '6 × 9 = ?', options: ['48','52','54','58'], answer: '54', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: 'A 9×-table trick: the digits of 9×7 add up to…', options: ['7','8','9','10'], answer: '9', difficulty: 3 },
    ],
  },

  // ── Grade 3 — Division ────────────────────────────────────────
  node_div_1: {
    id: 'node_div_1', districtId: 'district_division',
    title: 'Introduction to Division',
    explainer: 'Division means sharing equally. 12 ÷ 3 = 4 means "if you split 12 things into 3 equal groups, each group gets 4."',
    story: '🌿 The forest animals need to share food equally. Help them divide the harvest!',
    status: 'locked', difficulty: 2, xpReward: 85,
    questions: [
      { id: 'q1', type: 'mcq', text: '12 ÷ 4 = ?', options: ['2','3','4','6'], answer: '3', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: '20 ÷ 5 = ?', options: ['3','4','5','6'], answer: '4', difficulty: 1 },
      { id: 'q3', type: 'mcq', text: '18 ÷ 3 = ?', options: ['4','5','6','9'], answer: '6', difficulty: 1 },
      { id: 'q4', type: 'mcq', text: '8 cookies shared equally among 4 friends = ?', options: ['1','2','3','4'], answer: '2', difficulty: 1 },
      { id: 'q5', type: 'mcq', text: '35 ÷ 7 = ?', options: ['4','5','6','7'], answer: '5', difficulty: 2 },
    ],
  },
  node_div_2: {
    id: 'node_div_2', districtId: 'district_division',
    title: 'Division and Multiplication',
    explainer: 'Division and multiplication are opposites — they undo each other! If 4 × 5 = 20, then 20 ÷ 5 = 4. Use what you know to work out what you don\'t!',
    story: '⚖️ The Dell has a magic scale — what you multiply one way, you can undo the other!',
    status: 'locked', difficulty: 3, xpReward: 90,
    questions: [
      { id: 'q1', type: 'mcq', text: 'If 6 × 7 = 42, then 42 ÷ 6 = ?', options: ['5','6','7','8'], answer: '7', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: '8 × __ = 56, so 56 ÷ 8 = ?', options: ['5','6','7','8'], answer: '7', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: 'Which fact family includes 3 × 9 = 27?', options: ['27÷9=3','27÷3=9','Both','Neither'], answer: 'Both', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: '64 ÷ 8 = ?', options: ['6','7','8','9'], answer: '8', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: '9 × ? = 81, so 81 ÷ 9 = ?', options: ['7','8','9','10'], answer: '9', difficulty: 2 },
    ],
  },
  node_div_3: {
    id: 'node_div_3', districtId: 'district_division',
    title: 'Remainders',
    explainer: 'Sometimes things don\'t divide perfectly — the leftover is called the remainder! 13 ÷ 4 = 3 remainder 1. We write it as 3 R1.',
    story: '🍕 Not enough slices for everyone? Find out who gets extra and what\'s left over!',
    status: 'locked', difficulty: 3, xpReward: 100,
    questions: [
      { id: 'q1', type: 'mcq', text: '11 ÷ 3 = ? (with remainder)', options: ['3 R1','3 R2','4 R0','2 R5'], answer: '3 R2', difficulty: 2 },
      { id: 'q2', type: 'mcq', text: '17 ÷ 5 = ?', options: ['3 R1','3 R2','4 R1','4 R2'], answer: '3 R2', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: 'What is the remainder of 20 ÷ 6?', options: ['0','2','3','4'], answer: '2', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: '25 apples shared by 4. Remainder = ?', options: ['0','1','2','3'], answer: '1', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: 'Which has NO remainder? 19÷4, 21÷7, 23÷6, 17÷5', options: ['19÷4','21÷7','23÷6','17÷5'], answer: '21÷7', difficulty: 3 },
    ],
  },

  // ── Grade 4 — Fraction Operations ────────────────────────────
  node_frac_add_1: {
    id: 'node_frac_add_1', districtId: 'district_fraction_ops',
    title: 'Adding Fractions (Same Denominator)',
    explainer: 'When fractions have the same denominator, just add the tops! 1/5 + 2/5 = 3/5. The denominator stays the same — we\'re just adding pieces of the same size.',
    story: '🏗️ Two workers are building a fraction wall. Each carries a piece — how much do they carry together?',
    status: 'locked', difficulty: 2, xpReward: 100,
    questions: [
      { id: 'q1', type: 'mcq', text: '1/4 + 2/4 = ?', options: ['3/8','3/4','1/2','2/4'], answer: '3/4', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: '2/7 + 3/7 = ?', options: ['5/14','5/7','6/7','1/7'], answer: '5/7', difficulty: 1 },
      { id: 'q3', type: 'mcq', text: '1/6 + 4/6 = ?', options: ['5/12','5/6','4/6','1/2'], answer: '5/6', difficulty: 1 },
      { id: 'q4', type: 'mcq', text: '3/8 + 4/8 = ?', options: ['7/16','7/8','1/8','6/8'], answer: '7/8', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: '2/5 + 2/5 = ?', options: ['4/10','4/5','2/5','1/5'], answer: '4/5', difficulty: 2 },
    ],
  },
  node_frac_add_2: {
    id: 'node_frac_add_2', districtId: 'district_fraction_ops',
    title: 'Subtracting Fractions',
    explainer: 'To subtract fractions with the same denominator, subtract the numerators and keep the denominator. 5/6 − 2/6 = 3/6, which simplifies to 1/2.',
    story: '🌊 The tide is taking pieces away! Calculate what fraction of the shore remains.',
    status: 'locked', difficulty: 2, xpReward: 100,
    questions: [
      { id: 'q1', type: 'mcq', text: '3/4 − 1/4 = ?', options: ['2/4','1/2','3/4','2/8'], answer: '2/4', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: '5/6 − 2/6 = ?', options: ['3/6','1/2','3/0','7/6'], answer: '3/6', difficulty: 1 },
      { id: 'q3', type: 'mcq', text: '7/8 − 3/8 = ?', options: ['4/8','1/2','3/4','5/8'], answer: '4/8', difficulty: 1 },
      { id: 'q4', type: 'mcq', text: '6/7 − 2/7 = ?', options: ['4/7','3/7','5/7','4/14'], answer: '4/7', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: '9/10 − 4/10 in simplest form = ?', options: ['5/10','1/2','5/20','4/10'], answer: '1/2', difficulty: 2 },
    ],
  },
  node_frac_add_3: {
    id: 'node_frac_add_3', districtId: 'district_fraction_ops',
    title: 'Mixed Number Operations',
    explainer: 'A mixed number has a whole part and a fraction part, like 2½. To add: add the wholes, then the fractions. 1⅓ + 2⅓ = 3⅔!',
    story: '🍰 The baker is mixing recipes that use mixed numbers. Help measure the ingredients!',
    status: 'locked', difficulty: 3, xpReward: 120,
    questions: [
      { id: 'q1', type: 'mcq', text: '1½ + 1½ = ?', options: ['2','3','2½','2¼'], answer: '3', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: '2⅓ + 1⅓ = ?', options: ['3⅓','3⅔','4','2⅔'], answer: '3⅔', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: '3¾ − 1¼ = ?', options: ['2½','2¼','2¾','3½'], answer: '2½', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: 'Convert 7/4 to a mixed number', options: ['1¾','1½','2¼','1¼'], answer: '1¾', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: '4½ − 2¾ = ?', options: ['1¾','2¼','1¼','2¾'], answer: '1¾', difficulty: 3 },
    ],
  },

  // ── Grade 6 — More Variables & Algebra ───────────────────────
  node_var_2: {
    id: 'node_var_2', districtId: 'district_variables',
    title: 'Expressions with Variables',
    explainer: 'An expression is a math phrase with variables and numbers. "3x + 2" means "three times some number, plus two." We can evaluate it by substituting!',
    story: '📜 The ancient runes spell out expressions. Decode them by substituting the secret value!',
    status: 'locked', difficulty: 3, xpReward: 120,
    questions: [
      { id: 'q1', type: 'mcq', text: 'If x = 4, what is 2x + 1?', options: ['7','8','9','10'], answer: '9', difficulty: 2 },
      { id: 'q2', type: 'mcq', text: 'Evaluate 3y − 5 when y = 4', options: ['5','7','9','12'], answer: '7', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: 'Which expression has the value 14 when n = 3?', options: ['4n + 2','5n − 1','3n + 5','2n + 7'], answer: '4n + 2', difficulty: 3 },
      { id: 'q4', type: 'mcq', text: 'If a = 2, b = 3, find 2a + 3b', options: ['11','12','13','14'], answer: '13', difficulty: 3 },
      { id: 'q5', type: 'mcq', text: 'Simplify: x + x + x', options: ['x³','3x','x+3','3+x'], answer: '3x', difficulty: 2 },
    ],
  },
  node_var_3: {
    id: 'node_var_3', districtId: 'district_variables',
    title: 'Writing Expressions',
    explainer: 'We can write real situations as expressions. "Five more than a number" = n + 5. "Twice a number minus 3" = 2n − 3. Math as a language!',
    story: '🗝️ Translate the wizard\'s riddles into expressions to unlock the variable vault!',
    status: 'locked', difficulty: 3, xpReward: 120,
    questions: [
      { id: 'q1', type: 'mcq', text: '"Ten less than a number p" in math is…', options: ['10 − p','p − 10','10p','p + 10'], answer: 'p − 10', difficulty: 2 },
      { id: 'q2', type: 'mcq', text: '"Three times a number plus four" = ?', options: ['3 + 4n','3n + 4','4 × 3n','3n × 4'], answer: '3n + 4', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: 'Which sentence matches 2x − 5?', options: ['Five more than double x','Five less than double x','Double five minus x','x less than five'], answer: 'Five less than double x', difficulty: 3 },
      { id: 'q4', type: 'mcq', text: 'Sam has s stickers. He gives away 8. Expression for what\'s left?', options: ['s + 8','8 − s','s − 8','8s'], answer: 's − 8', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: 'A bag has n apples. Another has 3 times as many. Total?', options: ['n + 3','3n','n + 3n','4n'], answer: '4n', difficulty: 3 },
    ],
  },
  node_eq_1: {
    id: 'node_eq_1', districtId: 'district_equations',
    title: 'Solving One-Step Equations',
    explainer: 'An equation has an = sign meaning both sides balance. To solve, do the opposite operation. x + 5 = 9 → subtract 5 from both sides → x = 4.',
    story: '⚙️ The Equation Engine is jammed! Solve each equation to get the gears turning again.',
    status: 'locked', difficulty: 3, xpReward: 130,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Solve: x + 6 = 11', options: ['x=4','x=5','x=6','x=17'], answer: 'x=5', difficulty: 2 },
      { id: 'q2', type: 'mcq', text: 'Solve: y − 3 = 7', options: ['y=4','y=7','y=10','y=21'], answer: 'y=10', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: 'Solve: 4n = 28', options: ['n=5','n=6','n=7','n=8'], answer: 'n=7', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: 'Solve: m ÷ 3 = 9', options: ['m=3','m=12','m=27','m=6'], answer: 'm=27', difficulty: 3 },
      { id: 'q5', type: 'mcq', text: 'Solve: 15 − k = 8', options: ['k=6','k=7','k=8','k=23'], answer: 'k=7', difficulty: 2 },
    ],
  },
  node_eq_2: {
    id: 'node_eq_2', districtId: 'district_equations',
    title: 'Two-Step Equations',
    explainer: 'Two-step equations need two operations to solve. For 2x + 3 = 11: first subtract 3 (get 2x = 8), then divide by 2 (get x = 4). Work backwards!',
    story: '🔒 The double-locked safe needs two keys. Solve the two steps to open it!',
    status: 'locked', difficulty: 4, xpReward: 140,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Solve: 2x + 3 = 11', options: ['x=3','x=4','x=5','x=7'], answer: 'x=4', difficulty: 3 },
      { id: 'q2', type: 'mcq', text: 'Solve: 3y − 2 = 13', options: ['y=4','y=5','y=6','y=7'], answer: 'y=5', difficulty: 3 },
      { id: 'q3', type: 'mcq', text: 'Solve: 4n + 1 = 17', options: ['n=3','n=4','n=5','n=6'], answer: 'n=4', difficulty: 3 },
      { id: 'q4', type: 'mcq', text: 'Solve: 5m − 7 = 18', options: ['m=4','m=5','m=6','m=7'], answer: 'n=5', difficulty: 3 },
      { id: 'q5', type: 'mcq', text: 'Check: Is x = 3 a solution to 4x − 5 = 7?', options: ['Yes','No','Only if x>0','Need more info'], answer: 'Yes', difficulty: 3 },
    ],
  },
  node_eq_3: {
    id: 'node_eq_3', districtId: 'district_equations',
    title: 'Equations from Word Problems',
    explainer: 'Real problems can become equations! "A number plus 7 equals 15" → n + 7 = 15. Translate the words, solve the equation, interpret the answer.',
    story: '📰 The kingdom\'s message is written in riddles. Decode each one into an equation!',
    status: 'locked', difficulty: 4, xpReward: 140,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Sam has n coins. He earns 8 more and now has 20. Equation?', options: ['n−8=20','n+8=20','8n=20','n÷8=20'], answer: 'n+8=20', difficulty: 2 },
      { id: 'q2', type: 'mcq', text: 'From above, how many coins did Sam start with?', options: ['10','12','14','28'], answer: '12', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: 'Twice a number minus 3 equals 11. The number is…', options: ['4','5','6','7'], answer: '7', difficulty: 3 },
      { id: 'q4', type: 'mcq', text: 'Each box has 6 items. Total 30 items. Equation?', options: ['6+n=30','6n=30','n÷6=30','n−6=30'], answer: '6n=30', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: '3 tickets cost £21. Price per ticket (t)?', options: ['t=6','t=7','t=8','t=9'], answer: 't=7', difficulty: 2 },
    ],
  },
  node_expr_1: {
    id: 'node_expr_1', districtId: 'district_expressions',
    title: 'Terms and Coefficients',
    explainer: 'In "3x + 2y − 5": 3x, 2y and −5 are TERMS. 3 and 2 are COEFFICIENTS (numbers in front of variables). −5 is a CONSTANT. Know the parts!',
    story: '🗺️ The expression map has labeled regions. Learn the names of each territory!',
    status: 'locked', difficulty: 3, xpReward: 125,
    questions: [
      { id: 'q1', type: 'mcq', text: 'In 5x + 3, what is the coefficient of x?', options: ['3','5','x','5x'], answer: '5', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: 'How many terms are in 4a − 2b + 7?', options: ['2','3','4','1'], answer: '3', difficulty: 1 },
      { id: 'q3', type: 'mcq', text: 'Which is the constant in 6x + 9?', options: ['6','x','9','6x'], answer: '9', difficulty: 1 },
      { id: 'q4', type: 'mcq', text: 'The coefficient of y in −3y is…', options: ['3','-3','y','1'], answer: '-3', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: 'Like terms can be combined. Which are like terms?', options: ['3x and 3y','4x and 5x','2a and 2','x and x²'], answer: '4x and 5x', difficulty: 3 },
    ],
  },
  node_expr_2: {
    id: 'node_expr_2', districtId: 'district_expressions',
    title: 'Simplifying Expressions',
    explainer: 'Combine LIKE TERMS — terms with the same variable and power. 3x + 5x = 8x, but 3x + 5y cannot be combined (different variables).',
    story: '🌌 The expression expanse is cluttered! Tidy it up by combining like terms.',
    status: 'locked', difficulty: 4, xpReward: 135,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Simplify: 3x + 5x', options: ['8','8x','15x','8x²'], answer: '8x', difficulty: 1 },
      { id: 'q2', type: 'mcq', text: 'Simplify: 7y − 3y + 2', options: ['4y+2','4y','6y','10y'], answer: '4y+2', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: 'Simplify: 2a + 3b + 4a', options: ['9ab','6a+3b','9a+3b','6a+3b is correct'], answer: '6a+3b', difficulty: 2 },
      { id: 'q4', type: 'mcq', text: 'Which cannot be simplified further?', options: ['3x+5x','2y+2y','4a+3b','6z−2z'], answer: '4a+3b', difficulty: 2 },
      { id: 'q5', type: 'mcq', text: 'Simplify: 5m − 2m + 3n − n', options: ['3m+2n','7m+4n','3m+3n','5m+3n'], answer: '3m+2n', difficulty: 3 },
    ],
  },
  node_expr_3: {
    id: 'node_expr_3', districtId: 'district_expressions',
    title: 'Expanding Brackets',
    explainer: 'To expand 3(x + 2), multiply each term inside by 3: 3×x + 3×2 = 3x + 6. This is the distributive property — one of algebra\'s superpowers!',
    story: '🚪 The mystic gate opens only when you expand the sealed expression. Use your powers!',
    status: 'locked', difficulty: 4, xpReward: 145,
    questions: [
      { id: 'q1', type: 'mcq', text: 'Expand: 2(x + 3)', options: ['2x+3','2x+6','x+6','2+3x'], answer: '2x+6', difficulty: 2 },
      { id: 'q2', type: 'mcq', text: 'Expand: 4(y − 2)', options: ['4y−2','4y−8','4y+8','y−8'], answer: '4y−8', difficulty: 2 },
      { id: 'q3', type: 'mcq', text: 'Expand: 3(2a + 1)', options: ['6a+1','6a+3','3a+3','5a+3'], answer: '6a+3', difficulty: 3 },
      { id: 'q4', type: 'mcq', text: 'Expand and simplify: 2(x + 4) + 3x', options: ['5x+4','5x+8','2x+11','7x+4'], answer: '5x+8', difficulty: 3 },
      { id: 'q5', type: 'mcq', text: 'Which expansion is correct for 5(n − 3)?', options: ['5n−3','5n−15','n−15','5n+15'], answer: '5n−15', difficulty: 3 },
    ],
  },
}

// ── ThinkTales Story Beats ────────────────────────────────────────
export const STORY_BEATS = {
  realm_grade4_intro: {
    title: 'The Crystal Bridge Breaks',
    character: 'Princess Prism',
    avatar: '👸',
    lines: [
      'The Crystal Bridge that connects our islands has shattered into equal pieces!',
      'Only someone who understands fractions can tell us how many pieces there are...',
      'Each equal piece is a fraction of the whole. Will you help us rebuild it?',
    ],
  },
  node_equiv_1_unlock: {
    title: 'The Bridge Awakens',
    character: 'Intellia',
    avatar: '🤖',
    lines: [
      'Amazing! You discovered that 1/2 and 2/4 are actually the SAME amount!',
      'The bridge recognizes equivalent fractions and lights up!',
      'The Equivalent Grove is now open for exploration. Keep going!',
    ],
  },
}

// ── Progress Snapshot (initial state — all available for integration) ─
export const INITIAL_PROGRESS = {
  // Grade 1
  node_counting_1: 'available',
  node_counting_2: 'available',
  node_counting_3: 'available',
  node_skip_count_1: 'available',
  node_skip_count_2: 'available',
  node_skip_count_3: 'available',
  node_compare_1: 'available',
  node_compare_2: 'available',
  node_compare_3: 'available',
  // Grade 3
  node_mult_1: 'available',
  node_mult_2: 'available',
  node_mult_3: 'available',
  node_times_1: 'available',
  node_times_2: 'available',
  node_times_3: 'available',
  node_div_1: 'available',
  node_div_2: 'available',
  node_div_3: 'available',
  // Grade 4
  node_frac_intro_1: 'available',
  node_frac_intro_2: 'available',
  node_frac_intro_3: 'available',
  node_equiv_1: 'available',
  node_equiv_2: 'available',
  node_equiv_3: 'available',
  node_frac_add_1: 'available',
  node_frac_add_2: 'available',
  node_frac_add_3: 'available',
  // Grade 6
  node_var_1: 'available',
  node_var_2: 'available',
  node_var_3: 'available',
  node_eq_1: 'available',
  node_eq_2: 'available',
  node_eq_3: 'available',
  node_expr_1: 'available',
  node_expr_2: 'available',
  node_expr_3: 'available',
}
